rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#pry"
  recipients:
    - jrmair@gmail.com

branches:
  only:
    - master
